/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocohub.view;

/**
 *
 * @author Ruzbihan
 */
public class ManageOrders extends javax.swing.JDialog {

    /**
     * Creates new form ManageOrders
     */
    public ManageOrders(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        comboItemCode = new javax.swing.JComboBox<>();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        txtDate = new org.jdesktop.swingx.JXTextField();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        txtItemCode = new org.jdesktop.swingx.JXTextField();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtItemCode1 = new org.jdesktop.swingx.JXTextField();
        btnRemove = new org.jdesktop.swingx.JXButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtItemCode2 = new org.jdesktop.swingx.JXTextField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        txtItemName = new org.jdesktop.swingx.JXTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        txtItemName1 = new org.jdesktop.swingx.JXTextField();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        comboAvlbl = new javax.swing.JComboBox<>();
        btnRemoveOrder = new org.jdesktop.swingx.JXButton();
        btnRemove2 = new org.jdesktop.swingx.JXButton();
        btnRemoveOrderItem = new org.jdesktop.swingx.JXButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jXPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 4));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel6.setText("Item Code");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        comboItemCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboItemCode.setForeground(new java.awt.Color(51, 0, 0));
        jXPanel1.add(comboItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, 30));

        jXLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel3.setText("Date");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 50, 30));

        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        txtDate.setForeground(new java.awt.Color(51, 0, 0));
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDate.setSelectionColor(new java.awt.Color(51, 0, 0));
        jXPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 130, 30));

        jXLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel4.setText("Item Name");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, 30));

        txtItemCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        txtItemCode.setForeground(new java.awt.Color(51, 0, 0));
        txtItemCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtItemCode.setSelectionColor(new java.awt.Color(51, 0, 0));
        jXPanel1.add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 130, 30));

        jXLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel5.setText("Total Amount");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 100, 30));

        txtItemCode1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        txtItemCode1.setForeground(new java.awt.Color(51, 0, 0));
        txtItemCode1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtItemCode1.setSelectionColor(new java.awt.Color(51, 0, 0));
        jXPanel1.add(txtItemCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 190, 30));

        btnRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chocohub/images/edit.png"))); // NOI18N
        btnRemove.setText("Edit Order Item");
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jXPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 190, 40));

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Unit Price", "Availability"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);

        jXPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 810, 220));

        jXLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel7.setText("Item Code");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 30));

        txtItemCode2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        txtItemCode2.setForeground(new java.awt.Color(51, 0, 0));
        txtItemCode2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtItemCode2.setSelectionColor(new java.awt.Color(51, 0, 0));
        jXPanel1.add(txtItemCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 140, 30));

        jXLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel8.setText("Item Name");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 30));

        txtItemName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        txtItemName.setForeground(new java.awt.Color(51, 0, 0));
        txtItemName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtItemName.setSelectionColor(new java.awt.Color(51, 0, 0));
        jXPanel1.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 140, 30));

        jXLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel9.setText("Unit Price");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 90, 30));

        txtItemName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        txtItemName1.setForeground(new java.awt.Color(51, 0, 0));
        txtItemName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtItemName1.setSelectionColor(new java.awt.Color(51, 0, 0));
        jXPanel1.add(txtItemName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 140, 30));

        jXLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jXLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jXLabel10.setText("Availability");
        jXLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 80, 30));

        comboAvlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboAvlbl.setForeground(new java.awt.Color(51, 0, 0));
        comboAvlbl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jXPanel1.add(comboAvlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 60, 30));

        btnRemoveOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        btnRemoveOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chocohub/images/remove.png"))); // NOI18N
        btnRemoveOrder.setText("Remove Order");
        btnRemoveOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemoveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrderActionPerformed(evt);
            }
        });
        jXPanel1.add(btnRemoveOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 160, 40));

        btnRemove2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        btnRemove2.setText("Cancel");
        btnRemove2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove2ActionPerformed(evt);
            }
        });
        jXPanel1.add(btnRemove2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 190, 40));

        btnRemoveOrderItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        btnRemoveOrderItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chocohub/images/remove.png"))); // NOI18N
        btnRemoveOrderItem.setText("Remove Order Item");
        btnRemoveOrderItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemoveOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrderItemActionPerformed(evt);
            }
        });
        jXPanel1.add(btnRemoveOrderItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRemoveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveOrderActionPerformed

    private void btnRemove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove2ActionPerformed

    private void btnRemoveOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveOrderItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageOrders dialog = new ManageOrders(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnRemove;
    private org.jdesktop.swingx.JXButton btnRemove2;
    private org.jdesktop.swingx.JXButton btnRemoveOrder;
    private org.jdesktop.swingx.JXButton btnRemoveOrderItem;
    private javax.swing.JComboBox<String> comboAvlbl;
    private javax.swing.JComboBox<String> comboItemCode;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private org.jdesktop.swingx.JXTextField txtDate;
    private org.jdesktop.swingx.JXTextField txtItemCode;
    private org.jdesktop.swingx.JXTextField txtItemCode1;
    private org.jdesktop.swingx.JXTextField txtItemCode2;
    private org.jdesktop.swingx.JXTextField txtItemName;
    private org.jdesktop.swingx.JXTextField txtItemName1;
    // End of variables declaration//GEN-END:variables
}
